---
language: python
sudo: required
cache:
  - pip
  - apt
# addons:
#   apt:
#     packages:
#       - emacs24-nox
matrix:
  include:
    - python: 2.7
  allow_failures:
    - python: 3.5

install:
  - pip install -U flake8==2.6.2
script:
  - cd src/euslime
  - flake8 --ignore=E722,F821 .
  # Test suite currently isn't stable enough
  # - emacs --batch -L . -l euslime-config.el -f euslime-prepare-files
  # - ./tests/euslime_tests.py eus
